-- Bookkeeping RPCs resolve account defaults through account_for(role).
--
-- Generated by scratchpad/gen-roles.py from the LIVE definitions — the bodies
-- are untouched, only the parameter defaults and one resolution line per
-- account parameter. Retyping eleven money-path function bodies by hand would
-- have been the riskier way to do this.
--
-- Before: p_bank_account text DEFAULT '1930'   — the engine assumed Sweden.
-- After:  p_bank_account text DEFAULT NULL     + COALESCE(..., account_for('bank'))
--
-- Explicit callers are unaffected; passing a code still wins. See
-- 20260721180000_account-roles.sql for the role table and resolver.

CREATE OR REPLACE FUNCTION public.revalue_fixed_asset(p_asset_id uuid, p_new_value_cents bigint, p_reason text DEFAULT NULL::text, p_revaluation_date date DEFAULT CURRENT_DATE, p_impairment_account text DEFAULT NULL::text, p_reversal_account text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_asset public.fixed_assets; v_nbv BIGINT; v_delta BIGINT; v_amount BIGINT; v_je_id UUID;
BEGIN
  p_impairment_account := COALESCE(p_impairment_account, public.account_for('impairment'));
  p_reversal_account := COALESCE(p_reversal_account, public.account_for('impairment_reversal'));
  IF NOT (auth.role() = 'service_role' OR has_role(auth.uid(), 'admin')) THEN
    RAISE EXCEPTION 'revalue_fixed_asset: admin role required';
  END IF;
  IF p_new_value_cents IS NULL OR p_new_value_cents < 0 THEN RAISE EXCEPTION 'new_value_cents must be >= 0'; END IF;
  SELECT * INTO v_asset FROM public.fixed_assets WHERE id = p_asset_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Asset % not found', p_asset_id; END IF;
  IF v_asset.status = 'disposed' THEN RAISE EXCEPTION 'Asset is disposed'; END IF;

  v_nbv := v_asset.cost_cents - v_asset.accumulated_cents;
  v_delta := p_new_value_cents - v_nbv;
  IF v_delta = 0 THEN
    RETURN jsonb_build_object('success', true, 'asset_id', v_asset.id, 'message', 'New value equals current NBV — nothing to post', 'nbv_cents', v_nbv);
  END IF;

  v_je_id := NULL;
  IF v_delta < 0 THEN
    -- Impairment: Dt impairment loss / Cr accumulated
    v_amount := -v_delta;
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='journal_entries') THEN
      INSERT INTO public.journal_entries (entry_date, description, source, status)
      VALUES (p_revaluation_date, format('Impairment — %s%s', v_asset.name,
              CASE WHEN p_reason IS NOT NULL THEN ' ('||p_reason||')' ELSE '' END), 'fixed_asset_revaluation', 'posted') RETURNING id INTO v_je_id;
      INSERT INTO public.journal_entry_lines (journal_entry_id, account_code, debit_cents, credit_cents, description)
      VALUES (v_je_id, p_impairment_account, v_amount, 0, format('Impairment loss: %s', v_asset.name)),
             (v_je_id, v_asset.accumulated_account, 0, v_amount, format('Accum impairment: %s', v_asset.name));
    END IF;
    UPDATE public.fixed_assets SET
      accumulated_cents = accumulated_cents + v_amount,
      status = CASE WHEN (cost_cents - (accumulated_cents + v_amount)) <= salvage_cents THEN 'fully_depreciated' ELSE status END
    WHERE id = v_asset.id;
  ELSE
    -- Reversal of impairment / write-up: Dt accumulated / Cr reversal income.
    -- Capped so accumulated never goes negative (NBV never exceeds cost).
    v_amount := LEAST(v_delta, v_asset.accumulated_cents);
    IF v_amount <= 0 THEN
      RETURN jsonb_build_object('success', false, 'error',
        'Cannot revalue above original cost — no accumulated depreciation/impairment to reverse');
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='journal_entries') THEN
      INSERT INTO public.journal_entries (entry_date, description, source, status)
      VALUES (p_revaluation_date, format('Impairment reversal — %s%s', v_asset.name,
              CASE WHEN p_reason IS NOT NULL THEN ' ('||p_reason||')' ELSE '' END), 'fixed_asset_revaluation', 'posted') RETURNING id INTO v_je_id;
      INSERT INTO public.journal_entry_lines (journal_entry_id, account_code, debit_cents, credit_cents, description)
      VALUES (v_je_id, v_asset.accumulated_account, v_amount, 0, format('Reversal: %s', v_asset.name)),
             (v_je_id, p_reversal_account, 0, v_amount, format('Impairment reversal income: %s', v_asset.name));
    END IF;
    UPDATE public.fixed_assets SET
      accumulated_cents = accumulated_cents - v_amount,
      status = CASE WHEN status = 'fully_depreciated' THEN 'active' ELSE status END
    WHERE id = v_asset.id;
    v_amount := v_amount; -- positive for reversal
  END IF;

  INSERT INTO public.asset_revaluations (asset_id, revaluation_date, amount_cents, new_value_cents, reason, journal_entry_id)
  VALUES (v_asset.id, p_revaluation_date, CASE WHEN v_delta < 0 THEN -v_amount ELSE v_amount END, p_new_value_cents, p_reason, v_je_id);

  RETURN jsonb_build_object('success', true, 'asset_id', v_asset.id,
    'kind', CASE WHEN v_delta < 0 THEN 'impairment' ELSE 'reversal' END,
    'amount_cents', v_amount, 'journal_entry_id', v_je_id,
    'old_nbv_cents', v_nbv,
    'new_nbv_cents', CASE WHEN v_delta < 0 THEN v_nbv - v_amount ELSE v_nbv + v_amount END);
END; $function$;

CREATE OR REPLACE FUNCTION public.create_partial_match_with_variance(p_bank_transaction_id uuid, p_entity_type text, p_entity_id uuid, p_match_cents bigint, p_variance_cents bigint DEFAULT 0, p_variance_account_code text DEFAULT NULL::text, p_variance_account_name text DEFAULT 'Öresutjämning'::text, p_bank_gl_account text DEFAULT NULL::text, p_notes text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_bank public.bank_transactions;
  v_je_id uuid;
  v_match_id uuid;
BEGIN
  p_variance_account_code := COALESCE(p_variance_account_code, public.account_for('rounding_variance'));
  p_bank_gl_account := COALESCE(p_bank_gl_account, public.account_for('bank'));
  IF NOT (auth.role() = 'service_role'
          OR has_role(v_uid, 'admin') OR has_role(v_uid, 'approver')) THEN
    RAISE EXCEPTION 'forbidden';
  END IF;
  SELECT * INTO v_bank FROM public.bank_transactions WHERE id = p_bank_transaction_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'bank transaction not found'; END IF;

  -- If variance != 0, post a journal entry to move the variance
  IF p_variance_cents <> 0 THEN
    INSERT INTO public.journal_entries (entry_date, description, reference_number, status, source)
    VALUES (v_bank.transaction_date,
            'Partial-match variance: ' || COALESCE(p_notes,''),
            v_bank.reference, 'posted', 'reconciliation')
    RETURNING id INTO v_je_id;

    -- Variance sign convention:
    -- positive p_variance_cents = we received less than owed (short) → debit variance account, credit AR/etc.
    -- The two lines net to zero to keep JE balanced.
    IF p_variance_cents > 0 THEN
      INSERT INTO public.journal_entry_lines (journal_entry_id, account_code, account_name, debit_cents, credit_cents)
      VALUES
        (v_je_id, p_variance_account_code, p_variance_account_name, p_variance_cents, 0),
        (v_je_id, p_bank_gl_account, 'Bank', 0, p_variance_cents);
    ELSE
      INSERT INTO public.journal_entry_lines (journal_entry_id, account_code, account_name, debit_cents, credit_cents)
      VALUES
        (v_je_id, p_bank_gl_account, 'Bank', -p_variance_cents, 0),
        (v_je_id, p_variance_account_code, p_variance_account_name, 0, -p_variance_cents);
    END IF;
  END IF;

  INSERT INTO public.reconciliation_matches (
    bank_transaction_id, entity_type, entity_id, amount_cents,
    match_type, notes, created_by, variance_cents, variance_account_code, variance_journal_entry_id
  ) VALUES (
    p_bank_transaction_id, p_entity_type, p_entity_id, p_match_cents,
    'manual', p_notes, v_uid, p_variance_cents, p_variance_account_code, v_je_id
  ) RETURNING id INTO v_match_id;

  RETURN jsonb_build_object(
    'match_id', v_match_id,
    'journal_entry_id', v_je_id,
    'variance_cents', p_variance_cents
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.record_petty_cash_count(p_cash_account_code text, p_counted_cents bigint, p_diff_account_code text DEFAULT NULL::text, p_count_date date DEFAULT NULL::date, p_notes text DEFAULT NULL::text, p_currency text DEFAULT 'SEK'::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_date date := COALESCE(p_count_date, CURRENT_DATE);
  v_book bigint := 0;
  v_diff bigint;
  v_je_id uuid;
  v_count_id uuid;
BEGIN
  p_diff_account_code := COALESCE(p_diff_account_code, public.account_for('cash_difference'));
  IF NOT (auth.role() = 'service_role'
          OR has_role(v_uid, 'admin') OR has_role(v_uid, 'approver')) THEN
    RAISE EXCEPTION 'forbidden';
  END IF;

  SELECT COALESCE(SUM(l.debit_cents - l.credit_cents), 0)
    INTO v_book
    FROM public.journal_entry_lines l
    JOIN public.journal_entries e ON e.id = l.journal_entry_id
   WHERE l.account_code = p_cash_account_code
     AND e.status = 'posted'
     AND e.entry_date <= v_date;

  v_diff := p_counted_cents - v_book;

  IF v_diff <> 0 THEN
    INSERT INTO public.journal_entries (entry_date, description, status, source)
    VALUES (v_date,
            'Petty-cash count adjustment ' || p_cash_account_code,
            'posted', 'petty_cash_count')
    RETURNING id INTO v_je_id;

    IF v_diff > 0 THEN
      -- Counted more than book: debit cash, credit diff (income/gain)
      INSERT INTO public.journal_entry_lines (journal_entry_id, account_code, account_name, debit_cents, credit_cents)
      VALUES
        (v_je_id, p_cash_account_code, 'Cash', v_diff, 0),
        (v_je_id, p_diff_account_code, 'Cash difference', 0, v_diff);
    ELSE
      INSERT INTO public.journal_entry_lines (journal_entry_id, account_code, account_name, debit_cents, credit_cents)
      VALUES
        (v_je_id, p_diff_account_code, 'Cash difference', -v_diff, 0),
        (v_je_id, p_cash_account_code, 'Cash', 0, -v_diff);
    END IF;
  END IF;

  INSERT INTO public.petty_cash_counts (
    cash_account_code, count_date, counted_cents, book_balance_cents,
    difference_cents, diff_account_code, currency, notes, journal_entry_id, counted_by
  ) VALUES (
    p_cash_account_code, v_date, p_counted_cents, v_book,
    v_diff, p_diff_account_code, p_currency, p_notes, v_je_id, v_uid
  ) RETURNING id INTO v_count_id;

  RETURN jsonb_build_object(
    'count_id', v_count_id,
    'book_balance_cents', v_book,
    'difference_cents', v_diff,
    'journal_entry_id', v_je_id
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.mark_expense_report_paid(p_report_id uuid, p_method text DEFAULT 'manual'::text, p_reference text DEFAULT NULL::text, p_paid_at date DEFAULT NULL::date, p_bank_account text DEFAULT NULL::text, p_liability_account text DEFAULT NULL::text, p_notes text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_report record;
  v_total_cents bigint;
  v_entry_id uuid;
  v_payment_id uuid;
  v_date date;
BEGIN
  p_bank_account := COALESCE(p_bank_account, public.account_for('bank'));
  p_liability_account := COALESCE(p_liability_account, public.account_for('employee_liability'));
  SELECT * INTO v_report FROM expense_reports WHERE id = p_report_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Report not found');
  END IF;
  IF v_report.status <> 'booked' THEN
    RETURN jsonb_build_object('success', false, 'error', 'Only booked reports can be marked paid');
  END IF;

  SELECT COALESCE(SUM(amount_cents),0) INTO v_total_cents
  FROM expenses WHERE report_id = p_report_id;

  v_date := COALESCE(p_paid_at, CURRENT_DATE);

  INSERT INTO journal_entries (entry_date, description, source, status)
  VALUES (v_date, 'Payment of expense report ' || p_report_id::text, 'expense_payment', 'posted')
  RETURNING id INTO v_entry_id;

  INSERT INTO journal_entry_lines (journal_entry_id, account_code, debit_cents, credit_cents, description)
  VALUES
    (v_entry_id, p_liability_account, v_total_cents, 0, 'Settle liability'),
    (v_entry_id, p_bank_account, 0, v_total_cents, 'Bank payment');

  INSERT INTO expense_payments (report_id, user_id, amount_cents, method, reference, paid_at, journal_entry_id, notes, recorded_by)
  VALUES (p_report_id, v_report.user_id, v_total_cents, p_method::text, p_reference, v_date, v_entry_id, p_notes, auth.uid())
  RETURNING id INTO v_payment_id;

  UPDATE expense_reports
  SET status = 'paid'
  WHERE id = p_report_id;

  RETURN jsonb_build_object('success', true, 'report_id', p_report_id, 'payment_id', v_payment_id, 'journal_entry_id', v_entry_id);
END;
$function$;

CREATE OR REPLACE FUNCTION public.register_fixed_asset(p_name text, p_cost_cents bigint, p_useful_life_months integer, p_purchase_date date DEFAULT CURRENT_DATE, p_in_service_date date DEFAULT NULL::date, p_salvage_cents bigint DEFAULT 0, p_method text DEFAULT 'straight_line'::text, p_declining_rate numeric DEFAULT NULL::numeric, p_asset_account text DEFAULT NULL::text, p_depreciation_account text DEFAULT NULL::text, p_accumulated_account text DEFAULT NULL::text, p_credit_account text DEFAULT NULL::text, p_description text DEFAULT NULL::text, p_create_journal_entry boolean DEFAULT true)
 RETURNS fixed_assets
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_asset public.fixed_assets;
  v_je_id UUID;
BEGIN
  p_asset_account := COALESCE(p_asset_account, public.account_for('fixed_asset'));
  p_depreciation_account := COALESCE(p_depreciation_account, public.account_for('depreciation_expense'));
  p_accumulated_account := COALESCE(p_accumulated_account, public.account_for('accumulated_depreciation'));
  p_credit_account := COALESCE(p_credit_account, public.account_for('bank'));
  IF NOT (auth.role() = 'service_role' OR has_role(auth.uid(), 'admin')) THEN
    RAISE EXCEPTION 'register_fixed_asset: admin role required';
  END IF;

  INSERT INTO public.fixed_assets (
    name, description, cost_cents, salvage_cents, purchase_date, in_service_date,
    useful_life_months, depreciation_method, declining_rate,
    asset_account, depreciation_account, accumulated_account
  ) VALUES (
    p_name, p_description, p_cost_cents, COALESCE(p_salvage_cents,0),
    p_purchase_date, COALESCE(p_in_service_date, p_purchase_date),
    p_useful_life_months, p_method, p_declining_rate,
    p_asset_account, p_depreciation_account, p_accumulated_account
  ) RETURNING * INTO v_asset;

  IF p_create_journal_entry
     AND EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='journal_entries')
     AND EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='journal_entry_lines') THEN
    INSERT INTO public.journal_entries (entry_date, description, source, status)
    VALUES (
      v_asset.purchase_date,
      format('Acquisition of fixed asset: %s', v_asset.name),
      'fixed_asset_register',
      'posted'
    ) RETURNING id INTO v_je_id;

    INSERT INTO public.journal_entry_lines (journal_entry_id, account_code, debit_cents, credit_cents, description)
    VALUES
      (v_je_id, p_asset_account,  p_cost_cents, 0, format('Asset: %s', v_asset.name)),
      (v_je_id, p_credit_account, 0, p_cost_cents, format('Acquisition: %s', v_asset.name));
  END IF;

  RETURN v_asset;
END;
$function$;

CREATE OR REPLACE FUNCTION public.revalue_open_balances(p_revaluation_date date DEFAULT CURRENT_DATE, p_fx_gain_account text DEFAULT NULL::text, p_fx_loss_account text DEFAULT NULL::text, p_ar_account text DEFAULT NULL::text, p_ap_account text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_base TEXT;
  v_total_gain NUMERIC := 0;
  v_total_loss NUMERIC := 0;
  v_ar_lines INT := 0;
  v_ap_lines INT := 0;
  v_ar_delta NUMERIC := 0;
  v_ap_delta NUMERIC := 0;
  v_je_id UUID;
  rec RECORD;
  v_current_rate NUMERIC;
  v_delta NUMERIC;
BEGIN
  p_fx_gain_account := COALESCE(p_fx_gain_account, public.account_for('fx_gain'));
  p_fx_loss_account := COALESCE(p_fx_loss_account, public.account_for('fx_loss'));
  p_ar_account := COALESCE(p_ar_account, public.account_for('accounts_receivable'));
  p_ap_account := COALESCE(p_ap_account, public.account_for('accounts_payable'));
  IF NOT (auth.role() = 'service_role' OR has_role(auth.uid(), 'admin')) THEN
    RAISE EXCEPTION 'revalue_open_balances: admin role required';
  END IF;

  SELECT code INTO v_base FROM public.currencies WHERE is_base = true LIMIT 1;
  IF v_base IS NULL THEN
    RAISE EXCEPTION 'No base currency configured';
  END IF;

  -- Compute AR delta (open invoices in non-base currency)
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='invoices') THEN
    FOR rec IN
      SELECT id, currency, exchange_rate, total_cents, status
      FROM public.invoices
      WHERE currency <> v_base
        AND COALESCE(status::text, 'draft') NOT IN ('paid', 'cancelled', 'void')
    LOOP
      v_current_rate := public.get_exchange_rate(rec.currency, v_base, p_revaluation_date);
      -- delta in base currency = amount * (current_rate - booked_rate)
      v_delta := (rec.total_cents::NUMERIC / 100.0) * (v_current_rate - rec.exchange_rate);
      v_ar_delta := v_ar_delta + v_delta;
      v_ar_lines := v_ar_lines + 1;
    END LOOP;
  END IF;

  -- Compute AP delta (open POs / vendor bills in non-base currency)
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='purchase_orders') THEN
    FOR rec IN
      SELECT id, currency, exchange_rate, COALESCE(total_cents, 0) as total_cents, status
      FROM public.purchase_orders
      WHERE currency <> v_base
        AND COALESCE(status::text, 'draft') NOT IN ('paid', 'cancelled', 'closed')
    LOOP
      v_current_rate := public.get_exchange_rate(rec.currency, v_base, p_revaluation_date);
      v_delta := (rec.total_cents::NUMERIC / 100.0) * (v_current_rate - rec.exchange_rate);
      -- AP delta is opposite sign (liability)
      v_ap_delta := v_ap_delta - v_delta;
      v_ap_lines := v_ap_lines + 1;
    END LOOP;
  END IF;

  IF v_ar_delta > 0 THEN v_total_gain := v_total_gain + v_ar_delta; ELSE v_total_loss := v_total_loss + ABS(v_ar_delta); END IF;
  IF v_ap_delta > 0 THEN v_total_gain := v_total_gain + v_ap_delta; ELSE v_total_loss := v_total_loss + ABS(v_ap_delta); END IF;

  -- Create journal entry only if there's anything to book and accounting tables exist
  IF (v_total_gain > 0.01 OR v_total_loss > 0.01)
     AND EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='journal_entries')
     AND EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='journal_entry_lines') THEN

    INSERT INTO public.journal_entries (entry_date, description, source, status)
    VALUES (
      p_revaluation_date,
      format('FX revaluation %s — AR %s lines, AP %s lines', p_revaluation_date, v_ar_lines, v_ap_lines),
      'fx_revaluation',
      'posted'
    )
    RETURNING id INTO v_je_id;

    -- AR delta
    IF ABS(v_ar_delta) > 0.01 THEN
      IF v_ar_delta > 0 THEN
        -- AR increased in base value → Dt 1510, Cr 3960 (gain)
        INSERT INTO public.journal_entry_lines (entry_id, account_code, debit_cents, credit_cents, description)
        VALUES
          (v_je_id, p_ar_account, ROUND(v_ar_delta * 100), 0, 'FX revaluation AR'),
          (v_je_id, p_fx_gain_account, 0, ROUND(v_ar_delta * 100), 'Unrealized FX gain on AR');
      ELSE
        INSERT INTO public.journal_entry_lines (entry_id, account_code, debit_cents, credit_cents, description)
        VALUES
          (v_je_id, p_fx_loss_account, ROUND(ABS(v_ar_delta) * 100), 0, 'Unrealized FX loss on AR'),
          (v_je_id, p_ar_account, 0, ROUND(ABS(v_ar_delta) * 100), 'FX revaluation AR');
      END IF;
    END IF;

    -- AP delta
    IF ABS(v_ap_delta) > 0.01 THEN
      IF v_ap_delta > 0 THEN
        INSERT INTO public.journal_entry_lines (entry_id, account_code, debit_cents, credit_cents, description)
        VALUES
          (v_je_id, p_ap_account, ROUND(v_ap_delta * 100), 0, 'FX revaluation AP'),
          (v_je_id, p_fx_gain_account, 0, ROUND(v_ap_delta * 100), 'Unrealized FX gain on AP');
      ELSE
        INSERT INTO public.journal_entry_lines (entry_id, account_code, debit_cents, credit_cents, description)
        VALUES
          (v_je_id, p_fx_loss_account, ROUND(ABS(v_ap_delta) * 100), 0, 'Unrealized FX loss on AP'),
          (v_je_id, p_ap_account, 0, ROUND(ABS(v_ap_delta) * 100), 'FX revaluation AP');
      END IF;
    END IF;
  END IF;

  RETURN jsonb_build_object(
    'success', true,
    'revaluation_date', p_revaluation_date,
    'base_currency', v_base,
    'ar_lines', v_ar_lines,
    'ap_lines', v_ap_lines,
    'ar_delta', v_ar_delta,
    'ap_delta', v_ap_delta,
    'total_gain', v_total_gain,
    'total_loss', v_total_loss,
    'journal_entry_id', v_je_id
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.book_invoice_paid(p_invoice_id uuid, p_bank_account text DEFAULT NULL::text, p_ar_account text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_inv record;
  v_entry_id uuid;
  v_amount bigint;
BEGIN
  p_bank_account := COALESCE(p_bank_account, public.account_for('bank'));
  p_ar_account := COALESCE(p_ar_account, public.account_for('accounts_receivable'));
  SELECT * INTO v_inv FROM invoices WHERE id = p_invoice_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Invoice not found');
  END IF;

  IF EXISTS (SELECT 1 FROM journal_entries WHERE invoice_id = p_invoice_id AND source = 'invoice_payment') THEN
    RETURN jsonb_build_object('success', true, 'skipped', 'already booked');
  END IF;

  v_amount := COALESCE(v_inv.paid_amount_cents, v_inv.total_cents, 0);
  IF v_amount <= 0 THEN
    RETURN jsonb_build_object('success', false, 'error', 'Paid amount is zero');
  END IF;

  -- If issuance was never booked (e.g. legacy invoice), book it first so AR exists.
  PERFORM public.book_invoice_issued(p_invoice_id);

  INSERT INTO journal_entries (entry_date, description, source, invoice_id, status)
  VALUES (COALESCE(v_inv.paid_at::date, CURRENT_DATE),
          'Invoice ' || COALESCE(v_inv.invoice_number, p_invoice_id::text) || ' paid',
          'invoice_payment', p_invoice_id, 'posted')
  RETURNING id INTO v_entry_id;

  INSERT INTO journal_entry_lines (journal_entry_id, account_code, debit_cents, credit_cents, description)
  VALUES (v_entry_id, p_bank_account, v_amount, 0, 'Bank');
  INSERT INTO journal_entry_lines (journal_entry_id, account_code, debit_cents, credit_cents, description)
  VALUES (v_entry_id, p_ar_account, 0, v_amount, 'Settle accounts receivable');

  RETURN jsonb_build_object('success', true, 'invoice_id', p_invoice_id, 'journal_entry_id', v_entry_id, 'amount_cents', v_amount);
END;
$function$;

CREATE OR REPLACE FUNCTION public.book_invoice_issued(p_invoice_id uuid, p_ar_account text DEFAULT NULL::text, p_revenue_account text DEFAULT NULL::text, p_vat_account text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_inv record;
  v_entry_id uuid;
  v_net bigint;
  v_vat bigint;
  v_total bigint;
BEGIN
  p_ar_account := COALESCE(p_ar_account, public.account_for('accounts_receivable'));
  p_revenue_account := COALESCE(p_revenue_account, public.account_for('sales_revenue'));
  p_vat_account := COALESCE(p_vat_account, public.account_for('vat_output'));
  SELECT * INTO v_inv FROM invoices WHERE id = p_invoice_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Invoice not found');
  END IF;

  -- Idempotency: already booked?
  IF EXISTS (SELECT 1 FROM journal_entries WHERE invoice_id = p_invoice_id AND source = 'invoice_issued') THEN
    RETURN jsonb_build_object('success', true, 'skipped', 'already booked');
  END IF;

  v_total := COALESCE(v_inv.total_cents, 0);
  v_vat   := COALESCE(v_inv.tax_cents, 0);
  v_net   := COALESCE(v_inv.subtotal_cents, v_total - v_vat);
  IF v_total <= 0 THEN
    RETURN jsonb_build_object('success', false, 'error', 'Invoice total is zero');
  END IF;

  INSERT INTO journal_entries (entry_date, description, source, invoice_id, status)
  VALUES (COALESCE(v_inv.issue_date, CURRENT_DATE),
          'Invoice ' || COALESCE(v_inv.invoice_number, p_invoice_id::text) || ' issued',
          'invoice_issued', p_invoice_id, 'posted')
  RETURNING id INTO v_entry_id;

  INSERT INTO journal_entry_lines (journal_entry_id, account_code, debit_cents, credit_cents, description)
  VALUES (v_entry_id, p_ar_account, v_total, 0, 'Accounts receivable');
  INSERT INTO journal_entry_lines (journal_entry_id, account_code, debit_cents, credit_cents, description)
  VALUES (v_entry_id, p_revenue_account, 0, v_net, 'Revenue');
  IF v_vat > 0 THEN
    INSERT INTO journal_entry_lines (journal_entry_id, account_code, debit_cents, credit_cents, description)
    VALUES (v_entry_id, p_vat_account, 0, v_vat, 'Output VAT');
  END IF;

  RETURN jsonb_build_object('success', true, 'invoice_id', p_invoice_id, 'journal_entry_id', v_entry_id, 'total_cents', v_total);
END;
$function$;

CREATE OR REPLACE FUNCTION public.dispose_fixed_asset(p_asset_id uuid, p_sale_amount_cents bigint DEFAULT 0, p_disposal_date date DEFAULT CURRENT_DATE, p_proceeds_account text DEFAULT NULL::text, p_gain_account text DEFAULT NULL::text, p_loss_account text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_asset public.fixed_assets;
  v_nbv BIGINT;
  v_gain_loss BIGINT;
  v_je_id UUID;
BEGIN
  p_proceeds_account := COALESCE(p_proceeds_account, public.account_for('bank'));
  p_gain_account := COALESCE(p_gain_account, public.account_for('disposal_gain'));
  p_loss_account := COALESCE(p_loss_account, public.account_for('disposal_loss'));
  IF NOT (auth.role() = 'service_role' OR has_role(auth.uid(), 'admin')) THEN
    RAISE EXCEPTION 'dispose_fixed_asset: admin role required';
  END IF;

  SELECT * INTO v_asset FROM public.fixed_assets WHERE id = p_asset_id;
  IF v_asset.id IS NULL THEN RAISE EXCEPTION 'Asset not found'; END IF;
  IF v_asset.status = 'disposed' THEN RAISE EXCEPTION 'Asset already disposed'; END IF;

  v_nbv := v_asset.cost_cents - v_asset.accumulated_cents;
  v_gain_loss := COALESCE(p_sale_amount_cents,0) - v_nbv;

  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='journal_entries') THEN
    INSERT INTO public.journal_entries (entry_date, description, source, status)
    VALUES (p_disposal_date, format('Disposal: %s', v_asset.name), 'fixed_asset_disposal', 'posted')
    RETURNING id INTO v_je_id;

    -- Remove cost
    INSERT INTO public.journal_entry_lines (journal_entry_id, account_code, debit_cents, credit_cents, description)
    VALUES (v_je_id, v_asset.asset_account, 0, v_asset.cost_cents, 'Reverse cost');
    -- Remove accumulated depreciation
    IF v_asset.accumulated_cents > 0 THEN
      INSERT INTO public.journal_entry_lines (journal_entry_id, account_code, debit_cents, credit_cents, description)
      VALUES (v_je_id, v_asset.accumulated_account, v_asset.accumulated_cents, 0, 'Reverse accum depr');
    END IF;
    -- Cash proceeds
    IF COALESCE(p_sale_amount_cents,0) > 0 THEN
      INSERT INTO public.journal_entry_lines (journal_entry_id, account_code, debit_cents, credit_cents, description)
      VALUES (v_je_id, p_proceeds_account, p_sale_amount_cents, 0, 'Sale proceeds');
    END IF;
    -- Gain or loss
    IF v_gain_loss > 0 THEN
      INSERT INTO public.journal_entry_lines (journal_entry_id, account_code, debit_cents, credit_cents, description)
      VALUES (v_je_id, p_gain_account, 0, v_gain_loss, 'Gain on disposal');
    ELSIF v_gain_loss < 0 THEN
      INSERT INTO public.journal_entry_lines (journal_entry_id, account_code, debit_cents, credit_cents, description)
      VALUES (v_je_id, p_loss_account, ABS(v_gain_loss), 0, 'Loss on disposal');
    END IF;
  END IF;

  UPDATE public.fixed_assets
     SET status='disposed',
         disposed_at = p_disposal_date,
         disposed_amount_cents = p_sale_amount_cents
   WHERE id = p_asset_id;

  RETURN jsonb_build_object(
    'success', true,
    'asset_id', p_asset_id,
    'nbv_cents', v_nbv,
    'sale_cents', p_sale_amount_cents,
    'gain_loss_cents', v_gain_loss,
    'journal_entry_id', v_je_id
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.pay_vendor_invoice(p_vendor_invoice_id uuid, p_pay_date date DEFAULT CURRENT_DATE, p_bank_account text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_inv public.vendor_invoices;
  v_je_id uuid;
BEGIN
  p_bank_account := COALESCE(p_bank_account, public.account_for('bank'));
  SELECT * INTO v_inv FROM public.vendor_invoices WHERE id = p_vendor_invoice_id;
  IF v_inv.id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'Vendor invoice not found');
  END IF;
  IF v_inv.paid_at IS NOT NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'Vendor invoice already paid', 'paid_at', v_inv.paid_at);
  END IF;
  IF COALESCE(v_inv.total_cents, 0) <= 0 THEN
    RETURN jsonb_build_object('success', false, 'error', 'Vendor invoice has no positive total');
  END IF;

  INSERT INTO public.journal_entries (entry_date, description, status, source, vendor_id)
  VALUES (p_pay_date, 'Betalning leverantörsfaktura ' || COALESCE(v_inv.invoice_number, ''), 'posted', 'vendor_payment', v_inv.vendor_id)
  RETURNING id INTO v_je_id;

  -- account_name is auto-filled by the fill_journal_line_account_name trigger.
  INSERT INTO public.journal_entry_lines (journal_entry_id, account_code, debit_cents, credit_cents, description) VALUES
    (v_je_id, '2440', v_inv.total_cents, 0, 'Leverantörsskuld'),
    (v_je_id, p_bank_account, 0, v_inv.total_cents, 'Utbetalning');

  UPDATE public.vendor_invoices SET status = 'paid', paid_at = p_pay_date WHERE id = v_inv.id;

  RETURN jsonb_build_object(
    'success', true, 'vendor_invoice_id', v_inv.id, 'journal_entry_id', v_je_id,
    'total_cents', v_inv.total_cents, 'paid_at', p_pay_date, 'bank_account', p_bank_account
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.book_expense_report(p_report_id uuid, p_expense_account text DEFAULT NULL::text, p_vat_account text DEFAULT NULL::text, p_liability_account text DEFAULT NULL::text, p_entry_date date DEFAULT NULL::date)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_report record;
  v_total_cents bigint;
  v_vat_cents bigint;
  v_net_cents bigint;
  v_entry_id uuid;
  v_date date;
BEGIN
  p_expense_account := COALESCE(p_expense_account, public.account_for('expense_default'));
  p_vat_account := COALESCE(p_vat_account, public.account_for('vat_input'));
  p_liability_account := COALESCE(p_liability_account, public.account_for('employee_liability'));
  SELECT * INTO v_report FROM public.expense_reports WHERE id = p_report_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Report not found');
  END IF;
  IF v_report.status <> 'approved' THEN
    RETURN jsonb_build_object('success', false, 'error', 'Only approved reports can be booked');
  END IF;

  SELECT COALESCE(SUM(amount_cents),0), COALESCE(SUM(vat_cents),0)
  INTO v_total_cents, v_vat_cents
  FROM public.expenses WHERE report_id = p_report_id;

  v_net_cents := v_total_cents - v_vat_cents;
  v_date := COALESCE(p_entry_date, CURRENT_DATE);

  INSERT INTO public.journal_entries (entry_date, description, source, status)
  VALUES (v_date, 'Expense report ' || p_report_id::text, 'expense_report', 'posted')
  RETURNING id INTO v_entry_id;

  INSERT INTO public.journal_entry_lines (journal_entry_id, account_code, debit_cents, credit_cents, description)
  VALUES
    (v_entry_id, p_expense_account, v_net_cents, 0, 'Expense (net)'),
    (v_entry_id, p_vat_account, v_vat_cents, 0, 'Input VAT'),
    (v_entry_id, p_liability_account, 0, v_total_cents, 'Liability to employee');

  UPDATE public.expense_reports
  SET status = 'booked', journal_entry_id = v_entry_id
  WHERE id = p_report_id;

  RETURN jsonb_build_object('success', true, 'report_id', p_report_id, 'journal_entry_id', v_entry_id, 'total_cents', v_total_cents);
END;
$function$;

